version: '3'

tasks:
  deb-ubuntu:
    desc: Build the debian packages for Ubuntu
    dir: /work/work
    cmds:
      - rm -f debian
      - ln -s packaging/ubuntu debian
      - debuild -us -uc

  deb-ubuntu-bionic:
    desc: Build the debian packages for Ubuntu Bionic(18.04)
    dir: /work/work
    cmds:
      - rm -f debian
      - ln -s packaging/ubuntu-bionic debian
      - debuild -us -uc

  deb-debian-bookworm:
    desc: Build the debian packages for Debian Bookworm(12)
    dir: /work/work
    cmds:
      - rm -f debian
      - ln -s packaging/debian-bookworm debian
      - debuild -us -uc

  deb-clean:
    desc: Cleans after the debian package build
    cmds:
      - rm -f /work/*.deb /work/*.dsc /work/*.changes /work/*.tar.gz /work/*.build /work/*.buildinfo
      - rm -rf /work/work/debian

  build:
    desc: Build the project
    preconditions:
      - test -d /work/build
    dir: /work/build
    cmds:
      - rm -rf /work/build/.*
      - rm -rf /work/build/*
      - cmake /work/work/src
      - make

  ppa:
    desc: Upload the debian package to the ppa
    preconditions:
      - test -d /mnt/gnupg
    cmds:
      - rm -rf /root/.gnupg
      - cp -ra /mnt/gnupg /root/.gnupg 2>/dev/null | true
      - rm -rf /root/.gnupg/S.* /root/.gnupg/public-keys.d/.* /root/.gnupg/public-keys.d/*.lock
      - gpg-agent --daemon
      - debuild -S
      - dput ppa:wavelet-lab/usdr-lib /work/*.changes
